To do list add and remove
BHObserver/To-Do-List pull request #3
Opened 2023-08-19 22:50 UTC by BHObserver

In this branch-

- Add and Remove features are added.

2023-08-19 23:25 UTC, aamirkhan2478 requested changes
Hi @BHObserver, 

![](https://media2.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif?cid=ecf05e47k5uapdptg00nidbw3qaxx8iqgsusgaswci2c3uh1&rid=giphy.gif&ct=g)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Good Effort
✔️ Your design is good.
✔️ All linter passed

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-19 23:25 UTC, aamirkhan2478 commented on src/index.js
- [ ] Please fix your edit functionality for now your edit functionality is not working kindly fix it :+1: check below :point_down: screencast for more clarification :slightly_smiling_face: 

_**Note: Please watch this video in your Chrome browser because this video is one playable in Chrome browser**_

[screen-capture (26).webm](https://github.com/BHObserver/To-Do-List/assets/45226848/60dadde3-9632-4f2e-8822-da1fc66e0f40)

2023-08-19 23:25 UTC, aamirkhan2478 commented on src/index.js
> +  }
- [ ] Well done :clap: your implementation is good but you missed one functionality which is deleting a task that should update all remaining items `indexes`, so they represent the current list order and are unique so kindly fix this issue as well :+1: check below :point_down: screencast for more clarification :slightly_smiling_face: 

[screen-capture (27).webm](https://github.com/BHObserver/To-Do-List/assets/45226848/d770bfe8-2c1a-43b9-b8b7-069c8b74b4cc)

2023-08-22 05:41 UTC, Shedrack-Sunday approved these changes
Hi @BHObserver 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://github.com/krisbobo/blog-app/assets/50990925/76d09bb1-9dc7-46c0-be49-31f366afa4b8)


Highlights
- [x] Good project organization ✔️
- [x] Nice use of Javascript features ✔️ 
- [x] Kudus on meeting the requirements suggested  ✔️

### Confirmed view:





![image](https://github.com/BHObserver/To-Do-List/assets/50990925/5a15d7a7-0d48-4ec7-a23d-c1a190ff78d7)

Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-08-22 06:36 UTC, merged